#!/bin/bash

die() { rc=$?; (( $# )) && echo "$*" >&2; exit "$rc"; }

if [ -d "$HOME/.dotfiles" ]; then
    die "Dotfiles repo already set up..."
fi

cd $HOME

git clone --bare https://github.com/wheelerlaw/dotfiles.git $HOME/.dotfiles
function dotfiles {
    /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}
mkdir -p .dotfiles-backup
dotfiles checkout
if [ $? = 0 ]; then
    echo "Checked out dotfiles.";
    else
        echo "Backing up pre-existing dotfiles.";
        dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi;
dotfiles checkout
dotfiles config status.showUntrackedFiles no
